In [2]:
# Standard libraries
import numpy as np
import h5py
import pandas as pd
import matplotlib.pyplot as plt
from ipywidgets import interactive

# Append base directory
import os,sys,inspect
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
path1p = os.path.dirname(currentdir)
libpath = os.path.join(path1p, "lib")

sys.path.insert(0, libpath) 
print("Appended library directory", libpath)

# User libraries
from signal_lib import resample
from aux_functions import progress_bar
from data_io.qt_wrapper import gui_fnames, gui_fpath
import data_io.yaro.yaro_te_h5_lib as yaro_te_h5_lib
import plots.te_plots as te_plots

%load_ext autoreload
%autoreload 2

Appended library directory /home/alyosha/work/git/mesoscopic-functional-connectivity/codes/lib


In [3]:
# Get simulated H5 with TE
te_h5_fnames = gui_fnames("Select files with TE data", "./", "HDF5 (*.h5)")

In [16]:
# Extract data
data_dict = {}
for fname in te_h5_fnames:
    with h5py.File(fname, "r") as h5f:
        dataname = os.path.basename(fname[:-3])
        data_dict[dataname] = np.array(list(h5f['results'].values()))

In [17]:
P_THR = 0.01 # p-value threshold

# Process
for dataname, data in data_dict.items():
    te, lag, p = data
    nan_mask = np.isnan(p)
    p_nonan = np.copy(p)
    p_nonan[nan_mask] = 100
    pval_mask = p_nonan <= P_THR
    
    print("for", dataname, "mean NCONN is", np.mean(pval_mask))

for swipe_BivariateTE_sim_noise_lpf_trial_1 mean NCONN is 0.021105664488017428
for swipe_BivariateTE_sim_noise_pure_trial_1 mean NCONN is 0.03222222222222222
for swipe_MultivariateTE_sim_noise_lpf_trial_1 mean NCONN is 0.002042483660130719
for swipe_MultivariateTE_sim_noise_pure_trial_1 mean NCONN is 0.004861111111111111


In [49]:
y_lst

[array([0.81169887, 0.18830113]),
 array([0.64436264, 0.35563736]),
 array([0.37560807, 0.62439193]),
 array([0.88919187, 0.11080813]),
 array([0.25928701, 0.74071299]),
 array([0.89950246, 0.10049754]),
 array([0.35190573, 0.64809427]),
 array([0.73109959, 0.26890041]),
 array([0.35149846, 0.64850154]),
 array([0.60994478, 0.39005522]),
 array([0.75135933, 0.24864067]),
 array([0.56180268, 0.43819732]),
 array([0.50651386, 0.49348614]),
 array([0.20176293, 0.79823707]),
 array([0.05645686, 0.94354314]),
 array([0.32986561, 0.67013439]),
 array([0.63257065, 0.36742935]),
 array([0.23643433, 0.76356567]),
 array([0.51821156, 0.48178844]),
 array([0.68984851, 0.31015149]),
 array([0.66761456, 0.33238544]),
 array([0.23208527, 0.76791473]),
 array([0.56204354, 0.43795646]),
 array([0.02216902, 0.97783098]),
 array([0.63492716, 0.36507284]),
 array([0.51735038, 0.48264962]),
 array([0.54583754, 0.45416246]),
 array([0.94918815, 0.05081185]),
 array([0.37977923, 0.62022077]),
 array([0.7573